print("=== STEP 1 CONCLUSION: the delay chain ===")
print("  plan_start_ns           = 2.000000000 s   (admission planning begins)")
print("  plan_complete_ns        = 2.000005000 s   (+5 us planning delay)")
print("  network_release_ns      = 2.000005000 s   (flows released)")
print("  first packet at 84:1    = 2.000020000 s   (+15 us after release)")
print()
print("  command actuation delay      = 5 us   (plan_start -> network_release)")
print("  network propagation delay    = 15 us  (release -> first byte queued)")
print("  total observe->effect        = 20 us")
print()
print("=== CRITICAL FINDING: the credit did NOT act through a transient boost ===")
print("  legacy  admit_rate_bps = 15,625,000  (15.625 Mbps/flow)")
print("  credit  admit_rate_bps = 31,250,000  (31.250 Mbps/flow)  = exactly 2x")
print()
print("  The credit changed the flows' ADMITTED rate at t=2.000000, i.e. the")
print("  permanent per-flow grant, not a temporary boost on top of a base rate.")
print("  There is no 'base_rate_without_credit' recorded anywhere, because the")
print("  planner produced one rate and that rate WAS the credited one.")
print()
print("=== what that means for the lease design ===")
print("  A lease must restore 'the base rate without credit'. Today that value is")
print("  never computed: effectiveCapacityBps already contains the credit when the")
print("  admission grant is derived from it, so the credited grant is the only")
print("  grant in existence. Implementing the lease therefore requires computing")
print("  BOTH capacities each epoch:")
print("     C_base   = capacity with credit_bps = 0   (for lease expiry)")
print("     C_credit = capacity with credit_bps > 0   (while the lease is live)")
print("  and storing C_base per lease so expiry has something to fall back to.")
print()
print("  This is a real design addition, not a parameter change. It is also why")
print("  the boosted rate persisted for 2.6 ms: nothing existed to revert to.")
