C=10e9; H=175e-6; SOFT=524288.0; HARD=1048575.0
print("=== is the queue parked below hard by design or by luck? ===")
print("  YELLOW's lowest possible boost = 0  ->  sumR = C exactly")
print("  At sumR = C the queue neither fills nor drains: dQ/dt = 0.")
print("  So a queue at 1,044,749 B (99.6%% of hard) is a FIXED POINT, not")
print("  a transient.  It never crosses hard, so RED never fires, so no")
print("  drain ever happens.  That is a control defect, not a safe outcome.")
print()
print("=== what does the contract require? ===")
print("  RED: boost=0 AND drain>0, sumR<C, 'until predicted_delay returns to")
print("       the soft/hard band'.  RED is the ONLY state that drains.")
print("  So recovery depends on ENTERING red.  With Q asymptotic to hard from")
print("  below, entry never happens.")
print()
print("=== the oscillation ===")
print("  Q_stop uses max(excess_effective, excess_pending).  When a command to")
print("  LOWER boost is pending, excess_pending < excess_effective, so the max")
print("  keeps the OLD higher value -- correct for braking.  But once the lower")
print("  target confirms, Q_stop drops, the zone looks better, a HIGHER target")
print("  is commanded, and the cycle repeats every ~2*H_guard = 350 us.")
print("  Observed: 180 us spacing, alternating 0.0000C / 0.0222C / 0.0071C.")
print()
print("=== two candidate fixes, both inside the existing contract ===")
print("  (a) YELLOW hysteresis: once YELLOW is entered, require Q_stop to fall")
print("      below a re-arm level (e.g. 0.9*soft) before raising the target")
print("      again.  Removes the oscillation; does NOT create drain.")
print("  (b) RED entry on Q_safe, and RED exit only below soft: Q_safe already")
print("      includes the packetization margin, so with 64 senders it crosses")
print("      hard 67,072 B earlier -- but with 0 active senders (the tail) the")
print("      margin is 0 and this does nothing.  Insufficient alone.")
print()
print("  Neither (a) nor (b) makes a queue at sumR==C come down.")
print("  The gap is structural: YELLOW floor is sumR==C, and nothing drains")
print("  until RED.  Fix requires either")
print("    (c) YELLOW may also drain (contract currently says drain=0 in YELLOW), or")
print("    (d) RED entry uses a threshold BELOW hard so it fires before the")
print("        fixed point is reached.")
