import sys, os
sys.path.insert(0,'/work/simulation/experiment/scheme1_sba')
from controller_ref import *
print("=== is Q=527217 B a genuine equilibrium or a frozen state? ===")
q=527217.0
c=Controller()
c.boost_effective=0.0; c.drain_effective=0.0
u,p = c.signed_target(q)
print("  at Q=%.0f B: p=%.6f  u=%+.6f C" % (q,p,u/C))
print("  boost=%.6fC drain=%.6fC -> dQ/dt = %+.3f B/us" % (max(u,0)/C, max(-u,0)/C, u/8.0/1e6))
print()
print("  u=0 requires p = MAX_BOOST/(MAX_BOOST+MAX_DRAIN) = %.6f" % (MAX_BOOST/(MAX_BOOST+MAX_DRAIN)))
q_eq = SOFT_BYTES + MAX_BOOST/(MAX_BOOST+MAX_DRAIN)*(HARD_BYTES-SOFT_BYTES)
print("  -> Q_eq = %.0f B (%.2f us) = %.1f%% of hard" % (q_eq, q_eq*8/C*1e6, 100*q_eq/HARD_BYTES))
print()
print("  BUT the observed settle point is %.0f B, NOT %.0f B." % (q, q_eq))
print("  Difference = %.0f B.  So it is NOT the u=0 equilibrium." % (q_eq-q))
print()
print("=== what actually froze it? ===")
print("  The trace shows only 4 commands in 60 ms:")
print("    t=0      u=+0.3000C  GREEN")
print("    t=1250   u=+0.2987C  YELLOW")
print("    t=1255   u=+0.0000C  YELLOW   <-- descent")
print("    t=40315  u=+0.3000C  GREEN    <-- after batch end")
print()
print("  After t=1255 the effective target is u=0 -> dQ/dt=0 -> queue frozen.")
print("  The controller then never re-commands because:")
print("    rearm_required is set after the descent confirms, and")
print("    rearm line = %.0f B, but Q is stuck at %.0f B > rearm." % (REARM_BYTES,q))
print("  So positive boost is locked out AND drain is never commanded, because")
print("  the desired u at Q=%.0f is %+.4fC which is >0 and therefore" % (q,u/C))
print("  suppressed by the rearm lock -> min(0, current_u) = 0.")
print()
print("  RESULT: a NEW fixed point at u=0, created by my hysteresis rule.")
print("  It is safer than before (50.3%% vs 99.6%% of hard) but it is still a")
print("  frozen state, not the intended continuous equilibrium at %.1f%%." % (100*q_eq/HARD_BYTES))
