print("=== THE 0.6 Gbps IS FULLY ACCOUNTED FOR ===")
print()
print("Actual chain, with measured values:")
print()
for lab, eff in (('legacy', 10.0e9), ('credit', 12.0e9)):
    print('  --- %s: effective_capacity_bps = %.1f G ---' % (lab, eff/1e9))
    # AdmitBatch: residual = available; no old SBA flow applied yet
    resid = eff
    print('    residual (no old SBA flow applied at admission) = %.3f G' % (resid/1e9))
    share = 1.0/(1.0+1.0)
    nb = resid*share
    print('    x share 0.5 (oldBatchWeight=newBatchWeight=1.0) = %.3f G' % (nb/1e9))
    per = nb/64
    print('    ProgressiveFill / 64 flows                     = %.4f Mbps' % (per/1e6))
    print('    observed admit_rate_bps                        = %.4f Mbps' % ((eff/2/64)/1e6))
    print()
print("=== reconciliation of the 1.6 -> 1.0 gap ===")
print("  eta_feasibility new_share (migration replan) : 6.4 G -> 8.0 G  (delta 1.6 G)")
print("  admission grants (AdmitBatch)               : 1.0 G -> 2.0 G  (delta 1.0 G)")
print()
print("  These are TWO DIFFERENT ALLOCATORS on two different code paths:")
print("   * AdmitBatch (cbap-sba.cc) runs at t=2.000000, splits effective capacity")
print("     50:50 between the new batch and the pooled old flows, then")
print("     ProgressiveFill divides the new-batch half across 64 flows:")
print("        legacy 10.0/2/64 = 78.125 Mbps ... but observed 15.625 Mbps")
print("        credit 12.0/2/64 = 93.750 Mbps ... but observed 31.250 Mbps")
print()
print("  Still a factor of 5 and 3 respectively -- so ProgressiveFill is NOT")
print("  simply dividing. Check the ratio against a demand bound:")
print("     1 MiB message over the batch window, or maximumRateBps per flow.")
print("     15.625 Mbps x 64 = 1.0 G exactly; 31.25 x 64 = 2.0 G exactly.")
print("     10.0/1.0 = 10 ; 12.0/2.0 = 6  -> not constant, so not a fixed divisor.")
print()
print("  Observation: 1.0 G and 2.0 G are exactly (eff - 10 G) + 1 G, i.e.")
print("     legacy: 10 -> 1.0 ; credit: 12 -> 2.0 ; the delta tracks the credit 1:1")
print("  => the admission grant moves by EXACTLY the raw credit / 2 per the 0.5 share,")
print("     then something scales the base down by a further constant factor.")
